"""Execution node: run generated test cases against the target API.

Uses httpx with retry logic and a configurable rate limit, and also writes
the cases to disk as a standalone pytest suite the user can re-run.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path
from typing import Any
from urllib.parse import quote

import httpx

from app.config import settings
from app.models.state import AgentState
from app.models.testcase import ExecutionResult, TestCase

logger = logging.getLogger(__name__)

_MAX_ATTEMPTS = 3
_RETRYABLE_STATUSES = {429, 503}
_MAX_CAPTURED_BODY = 100_000


def resolve_path(template: str, path_params: dict[str, str]) -> str:
    """Substitute ``{placeholders}`` in a templated path (URL-encoded)."""
    resolved = template
    for name, value in path_params.items():
        resolved = resolved.replace("{" + name + "}", quote(str(value), safe=""))
    return resolved


def _parse_body(case: TestCase) -> tuple[Any | None, str | None]:
    """Decode the case's JSON body string; fall back to raw text."""
    if case.body is None or case.body == "":
        return None, None
    try:
        return json.loads(case.body), None
    except json.JSONDecodeError:
        return None, case.body


def _capture_body(response: httpx.Response) -> Any:
    """Return the response body as JSON if possible, else truncated text."""
    try:
        return response.json()
    except (json.JSONDecodeError, ValueError):
        return response.text[:_MAX_CAPTURED_BODY]


def execute_case(
    client: httpx.Client, case: TestCase, base_url: str, auth_headers: dict[str, str]
) -> ExecutionResult:
    """Run one test case with retries on transport errors and 429/503."""
    url = base_url.rstrip("/") + resolve_path(case.path, case.path_params)
    headers = {"Accept": "application/json", **auth_headers, **case.headers}
    json_body, raw_body = _parse_body(case)
    if raw_body is not None:
        headers.setdefault("Content-Type", "application/json")

    last_error: str | None = None
    for attempt in range(1, _MAX_ATTEMPTS + 1):
        started = time.perf_counter()
        try:
            response = client.request(
                case.method,
                url,
                params=case.query_params or None,
                headers=headers,
                json=json_body,
                content=raw_body,
            )
        except httpx.HTTPError as exc:
            last_error = f"{type(exc).__name__}: {exc}"
            if attempt < _MAX_ATTEMPTS:
                time.sleep(0.5 * 2**attempt)
                continue
            return ExecutionResult(case=case, error=last_error)

        latency_ms = (time.perf_counter() - started) * 1000
        if response.status_code in _RETRYABLE_STATUSES and attempt < _MAX_ATTEMPTS:
            time.sleep(0.5 * 2**attempt)
            continue
        return ExecutionResult(
            case=case,
            status_code=response.status_code,
            latency_ms=round(latency_ms, 1),
            response_body=_capture_body(response),
        )
    return ExecutionResult(case=case, error=last_error or "request failed")


_CONFTEST = '''"""Fixtures for the generated test suite."""
import os

import pytest


@pytest.fixture(scope="session")
def base_url() -> str:
    """Target API base URL; override with the TARGET_BASE_URL env var."""
    return os.getenv("TARGET_BASE_URL", {default_url!r}).rstrip("/")
'''

_TEST_MODULE = '''"""Generated by the API Test Agent — re-run any time with `pytest`.

Each case asserts the HTTP status code the agent expected when it was
generated. Set TARGET_BASE_URL to point the suite at another deployment.
"""
import json
from pathlib import Path
from urllib.parse import quote

import httpx
import pytest

CASES = json.loads((Path(__file__).parent / "cases.json").read_text(encoding="utf-8"))


def _resolve(template: str, params: dict) -> str:
    for name, value in params.items():
        template = template.replace("{" + name + "}", quote(str(value), safe=""))
    return template


@pytest.mark.parametrize("case", CASES, ids=[c["id"] + "_" + c["name"] for c in CASES])
def test_case(case: dict, base_url: str) -> None:
    body = case.get("body")
    json_body = None
    if body:
        try:
            json_body = json.loads(body)
            body = None
        except json.JSONDecodeError:
            pass
    response = httpx.request(
        case["method"],
        base_url + _resolve(case["path"], case["path_params"]),
        params=case["query_params"] or None,
        headers={"Accept": "application/json", **case["headers"]},
        json=json_body,
        content=body,
        timeout=30,
    )
    assert response.status_code == case["expected_status"], (
        f"{case['method']} {case['path']} returned {response.status_code}, "
        f"expected {case['expected_status']}: {response.text[:300]}"
    )
'''


def write_pytest_suite(report_id: str, target_url: str, cases: list[TestCase]) -> str:
    """Write a self-contained pytest suite for the cases; return its directory."""
    suite_dir = Path(settings.generated_tests_dir) / report_id
    suite_dir.mkdir(parents=True, exist_ok=True)
    (suite_dir / "cases.json").write_text(
        json.dumps([c.model_dump() for c in cases], indent=2), encoding="utf-8"
    )
    (suite_dir / "conftest.py").write_text(
        _CONFTEST.format(default_url=target_url), encoding="utf-8"
    )
    (suite_dir / "test_generated.py").write_text(_TEST_MODULE, encoding="utf-8")
    return str(suite_dir)


def execute_tests_node(state: AgentState) -> dict[str, Any]:
    """LangGraph node: execute all cases (rate-limited) and export pytest files."""
    results: list[ExecutionResult] = []
    notes = list(state.notes)
    min_interval = 1.0 / settings.rate_limit_rps

    with httpx.Client(timeout=settings.request_timeout, follow_redirects=True) as client:
        for case in state.test_cases:
            results.append(
                execute_case(client, case, state.target_base_url, state.auth_headers)
            )
            time.sleep(min_interval)

    pytest_dir: str | None = None
    if state.test_cases:
        pytest_dir = write_pytest_suite(
            state.report_id, state.target_base_url, state.test_cases
        )
        notes.append(f"Re-runnable pytest suite written to {pytest_dir}")

    errors = sum(1 for r in results if r.error)
    logger.info("Executed %d cases (%d transport errors)", len(results), errors)
    return {"execution_results": results, "pytest_dir": pytest_dir, "notes": notes}
